# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0090_auto_20200708_0907'),
        ('owner', '0006_auto_20200605_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditionalusernames',
            name='id_service_owner',
        ),
        migrations.RemoveField(
            model_name='external',
            name='id_contact_info',
        ),
        migrations.RemoveField(
            model_name='internal',
            name='id_contact_info',
        ),
        migrations.RemoveField(
            model_name='serviceowner',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='serviceowner',
            name='id_service_owner',
        ),
        migrations.DeleteModel(
            name='AditionalUsernames',
        ),
        migrations.DeleteModel(
            name='External',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Internal',
        ),
        migrations.DeleteModel(
            name='ServiceOwner',
        ),
    ]
